import image2 from "../../images/RestaurantForCard1.webp"
import image3 from "../../images/RestaurantForCard2.jpeg"
import image4 from "../../images/RestaurantForCard3.avif"
import closedRestaurant from "../../images/closedRestaurant.jpg"

export const CarouselItems = [
  {
    image: image4,
    alt: "",
    description: "Mira",
    description2: "★ 4.2  Very Good",
    description3: "Nicest place for burgers",
    description4: "Comfort food",
    link: "/mira",
  },
  {
    image: image2,
    alt: "",
    description: "Kara Fin",
    description2: "★ 4.2  Very Good",
    description3: "Nicest place for burgers",
    description4: "Comfort food",
    link: "/kara-fin",
  },
  {
    image: closedRestaurant,
    text: "This restaurant is closed",
    alt: "",
    description: "‘T Kuyltje",
    description2: "★ 4.2  Very Good",
    description3: "Nicest place for burgers",
    description4: "Comfort food",
    link: "",
  },
  {
    image: image2,
    alt: "",
    description: "Kara Fin",
    description2: "★ 4.2  Very Good",
    description3: "Nicest place for burgers",
    description4: "Comfort food",
    link: "/kara-fin",
  },
  {
    image: image4,
    alt: "",
    description: "Mira",
    description2: "★ 4.2  Very Good",
    description3: "Nicest place for burgers",
    description4: "Comfort food",
    link: "/mira",
  },
  {
    image: image2,
    alt: "",
    description: "Kara Fin",
    description2: "★ 4.2  Very Good",
    description3: "Nicest place for burgers",
    description4: "Comfort food",
    link: "/kara-fin",
  },
  {
    image: image3,
    alt: "",
    description: "‘T Kuyltje",
    description2: "★ 4.2  Very Good",
    description3: "Nicest place for burgers",
    description4: "Comfort food",
    link: "/t-kuyltje",
  },
  {
    image: image2,
    alt: "",
    description: "Kara Fin",
    description2: "★ 4.2  Very Good",
    description3: "Nicest place for burgers",
    description4: "Comfort food",
    link: "/kara-fin",
  },
]
